---
# Homepage configuration 相关图标
# See https://fontawesome.com/v5/search for icons options

title: "Home"
subtitle: "home.ono.ee"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon


header: true
footer: false
# set false of true if you want to hide it.

# Set the default layout and color scheme 设置默认布局和配色方案
defaults:
  layout: list # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'


# Will load Dracula theme.
stylesheet:
  - "assets/themes/catppucin/catppuccin-mocha.css"
# assets/themes/custom/custom.css
# assets/themes/catppucin/catppuccin-mocha.css


# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "首页"
    icon: "fab fa-hexagon"
    url: "#"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Awesome app"
        logo: "assets/tools/sample.png"
        subtitle: "Bookmark example"
        tag: "app"
        keywords: "self hosted reddit"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank" # optional html a tag target attribute
      - name: "Another one"
        logo: "assets/tools/sample2.png"
        subtitle: "Another application"
        tag: "app"
        url: "#"
